#项目参数配置
server:
  port: 1902
  tomcat:
    max-http-form-post-size: 8192
    uri-encoding: utf-8 #编码格式
  servlet:
    context-path: /study    #设置项目名  SpringBoot版本2.X的设置方式
    session:
      timeout: 30m  #session生命周期

#框架参数配置
spring:
  #mysql数据库相关配置      时区问题，serverTimezone=UTC，将这个UTC改成serverTimezone=CTT即可，CTT（Asia&Shanghai）北京时间。UTC：世界统一时间，世界标准时间，国际协调时间
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://127.0.0.1:3306/k_line?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF8&autoReconnect=true&rewriteBatchedStatements=true?tinyInt1isBit=false
    url: jdbc:mysql://192.168.1.9:3306/k_line?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF8&autoReconnect=true&rewriteBatchedStatements=true
    username: root
    password: 123456
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5

  #统一处理json时间返回问题  实体对象 属性注解方式：@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", locale = "zh", timezone = "GMT+8")
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  #redis
  redis:
    #redis机器ip
    hostname: 127.0.0.1
    #redis端口
    port: 6379
    #redis密码
    password:
    #redis超时时间（毫秒），如果不设置，取默认值2000
    timeout: 10000
    #最大空闲数
    maxIdle: 300
    #连接池的最大数据库连接数。设为0表示无限制,如果是jedis 2.4以后用redis.maxTotal
    #maxActive=600
    #控制一个pool可分配多少个jedis实例,用来替换上面的redis.maxActive,如果是jedis 2.4以后用该属性
    maxTotal: 1000
    #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
    maxWaitMillis: 1000
    #连接的最小空闲时间 默认1800000毫秒(30分钟)
    minEvictableIdleTimeMillis: 300000
    #每次释放连接的最大数目,默认3
    numTestsPerEvictionRun: 1024
    #逐出扫描的时间间隔(毫秒) 如果为负数,则不运行逐出线程, 默认-1
    timeBetweenEvictionRunsMillis: 30000
    #是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个
    testOnBorrow: true
    #在空闲时检查有效性, 默认false
    testWhileIdle: true

    #redis集群配置
    #spring.cluster.nodes=192.168.1.1:7001,192.168.1.1:7002,192.168.1.1:7003,192.168.1.1:7004,192.168.1.1:7005,192.168.1.1:7006
    #spring.cluster.max-redirects=3

    #哨兵模式
    #sentinel.host1=192.168.1.1
    #sentinel.port1=26379

    #sentinel.host2=192.168.1.2
    #sentinel.port2=26379

